repos:

-   repo: local
    hooks:
    -   id: ruff-format
        name: ruff format
        stages: [pre-commit, pre-push, manual]
        language: system
        entry: ruff
        args: 
        -   "format"
        -   "--config"
        -   ".github/ruff.toml"
        -   "stats4science/"
        -   "examples/"
        -   "tests/"
        always_run: true
        pass_filenames: false

-   repo: local
    hooks:
    -   id: ruff
        name: ruff
        stages: [pre-commit, pre-push, manual]
        language: system
        entry: ruff
        args: 
        -   "check"
        -   "--fix"
        -   "--config"
        -   ".github/ruff.toml"
        -   "stats4science/"
        -   "examples/"
        -   "tests/"
        always_run: true
        pass_filenames: false


-   repo: local
    hooks:
    -   id: mypy
        name: mypy
        stages: [pre-commit, pre-push, manual]
        language: system
        entry: mypy
        args:
        -   "--check-untyped-defs"
        -   "--ignore-missing-imports"
        -   "stats4science/"
        -   "examples/"
        -   "tests/"
        always_run: true
        pass_filenames: false

